CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name varchar NOT NULL,
	description varchar NULL,
	available bool NOT NULL,
	owner_id BIGINT NULL,
	CONSTRAINT items_pk PRIMARY KEY (id),
	CONSTRAINT items_users_fk FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking (
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	item_id BIGINT NOT NULL,
	booking_start timestamp NOT NULL,
	booking_end timestamp NOT NULL,
	booker_id BIGINT NOT NULL,
	status varchar NOT NULL,
	CONSTRAINT booking_pk PRIMARY KEY (id),
	CONSTRAINT booking_items_fk FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT booking_users_fk FOREIGN KEY (booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
	id BIGINT GENERATED ALWAYS AS IDENTITY NOT NULL,
	text varchar NOT NULL,
	item_id BIGINT NOT NULL,
	user_id BIGINT NOT NULL,
	created timestamp NOT NULL,
	CONSTRAINT comments_pk PRIMARY KEY (id),
	CONSTRAINT comments_items_fk FOREIGN KEY (item_id) REFERENCES items(id),
	CONSTRAINT comments_users_fk FOREIGN KEY (user_id) REFERENCES users(id)
);